import pandas as pd
import os
import json

DATA_PATH = "data/raw_ticks.ndjson"


def load_tick_data():
    """
    Loads tick data from NDJSON file generated by Binance WebSocket tool.
    Safely handles empty or missing files.
    """

    if not os.path.exists(DATA_PATH):
        return pd.DataFrame(columns=["timestamp", "symbol", "price", "size"])

    if os.stat(DATA_PATH).st_size == 0:
        return pd.DataFrame(columns=["timestamp", "symbol", "price", "size"])

    records = []

    with open(DATA_PATH, "r") as f:
        for line in f:
            try:
                record = json.loads(line)
                records.append(record)
            except json.JSONDecodeError:
                continue

    if not records:
        return pd.DataFrame(columns=["timestamp", "symbol", "price", "size"])

    df = pd.DataFrame(records)

    # Ensure correct column names
    df.rename(columns={
        "ts": "timestamp",
        "price": "price",
        "size": "size",
        "symbol": "symbol"
    }, inplace=True)

    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values("timestamp")

    return df
